# Generated by Django 5.0.6 on 2026-07-02 02:15

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='is_work_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='nysc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='nysc_certs/', validators=[apps.common.validators.validate_document_upload]),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='nysc_status',
            field=models.CharField(choices=[('completed', 'Completed (has certificate)'), ('serving', 'Currently serving'), ('exempted', 'Exempted'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AlterField(
            model_name='artisanportfolioitem',
            name='image',
            field=models.FileField(upload_to='portfolio/', validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.CreateModel(
            name='ArtisanJobVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='job_videos/', validators=[apps.common.validators.validate_video_upload])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_videos', to='accounts.artisanprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
