# Generated by Django 5.0.6 on 2026-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_artisanprofile_is_work_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
