# Generated by Django 5.0.6 on 2026-07-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_artisanprofile_show_phone'),
        ('accounts', '0004_backfill_paired_profiles'),
    ]

    operations = [
    ]
