# Generated by Django 5.0.6 on 2026-07-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employer_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='phone',
        ),
    ]
