# Generated by Django 5.0.6 on 2026-07-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('booking', 'Booking'), ('subscription', 'Subscription'), ('job_posting', 'Job posting'), ('verification', 'Verification'), ('cv_service', 'CV Service')], max_length=20),
        ),
    ]
